#!/usr/bin/env node
import { Command } from 'commander';
import * as dotenv from 'dotenv';
import { resolve } from 'path';
import { Keypair, Operation, rpc, TransactionBuilder, Networks, Address, nativeToScVal } from '@stellar/stellar-sdk';
import { Client } from './bindings/stream'; // Auto-generated by Sprint 2

// Securely load environment variables
dotenv.config({ path: resolve(__dirname, '../../.env') });

const program = new Command();

program
  .name('orbitstream')
  .description('CLI to deploy and manage OrbitStream continuous funding contracts on Soroban')
  .version('0.1.0');

program
  .command('init')
  .description('Initialize a new funding stream configuration')
  .requiredOption('-r, --receiver <address>', 'The Stellar address of the open-source maintainer')
  .requiredOption('-t, --token <address>', 'The contract address of the token (e.g., USDC)')
  .requiredOption('-f, --flow-rate <amount>', 'The amount of tokens to stream per second')
  .action(async (options) => {
    const deployerSecret = process.env.SOROBAN_SECRET_KEY;
    const streamContractId = process.env.STREAM_CONTRACT_ID;

    if (!deployerSecret) {
      console.error("FATAL: SOROBAN_SECRET_KEY is missing from the .env file.");
      process.exit(1);
    }
    if (!streamContractId) {
      console.error("FATAL: STREAM_CONTRACT_ID is missing from the .env file. Run 'make deploy' first.");
      process.exit(1);
    }

    try {
      console.log(`Targeting Stream Contract: ${streamContractId}`);
      
      // Cryptographically derive the keypair in-memory
      const keypair = Keypair.fromSecret(deployerSecret);
      console.log(`Loaded deployer identity: ${keypair.publicKey()}`);

      // Initialize the generated Soroban Client
      const client = new Client({
        networkPassphrase: 'Test SDF Network ; September 2015',
        contractId: streamContractId,
        rpcUrl: 'https://soroban-testnet.stellar.org:443',
        publicKey: keypair.publicKey(),
      });

      console.log('Building and submitting transaction to Testnet...');
      
      // Execute the on-chain init method via the generated TS bindings
      // The bindings automatically map JS types to Rust types (flow_rate -> u64)
      const txResponse = await client.init({
        sender: keypair.publicKey(),
        receiver: options.receiver,
        token: options.token,
        flow_rate: BigInt(options.flowRate)
      });

      console.log('SUCCESS: Transaction confirmed on ledger!');
      console.log('Transaction Result:', txResponse);

    } catch (error: any) {
      console.error("FATAL: Transaction failed on-chain.");
      // Unpack VM panics or RPC errors for developer visibility
      console.error(error?.response?.data || error.message || error);
      process.exit(1);
    }
  });

program
  .command('get')
  .description('Retrieve an active funding stream configuration from the blockchain')
  .requiredOption('-s, --sender <address>', 'The Stellar address of the sender')
  .requiredOption('-r, --receiver <address>', 'The Stellar address of the receiver')
  .action(async (options) => {
    const streamContractId = process.env.STREAM_CONTRACT_ID;

    if (!streamContractId) {
      console.error("FATAL: STREAM_CONTRACT_ID is missing from the .env file. Run 'make deploy' first.");
      process.exit(1);
    }

    try {
      console.log(`Querying Stream Contract: ${streamContractId}`);
      
      // Initialize the generated Soroban Client without a signer (read-only)
      const client = new Client({
        networkPassphrase: 'Test SDF Network ; September 2015',
        contractId: streamContractId,
        rpcUrl: 'https://soroban-testnet.stellar.org:443',
      });

      console.log(`Fetching stream from ${options.sender} to ${options.receiver}...`);
      
      const result = await client.get_stream({
        sender: options.sender,
        receiver: options.receiver,
      });

      console.log('SUCCESS: Stream configuration retrieved!');
      // The generated bindings automatically unwrap the Rust StreamConfig struct
      console.log(`Token: ${result.token}`);
      console.log(`Flow Rate: ${result.flow_rate.toString()} tokens/sec`);

    } catch (error: any) {
      console.error("FATAL: Failed to retrieve stream. It may not exist.");
      console.error(error?.response?.data || error.message || error);
      process.exit(1);
    }
  });

program
  .command('claim')
  .description('Claim accrued tokens from an active funding stream')
  .requiredOption('-s, --sender <address>', 'The Stellar address of the sender')
  .requiredOption('-r, --receiver <address>', 'The Stellar address of the receiver')
  .action(async (options) => {
    const secretKey = process.env.SOROBAN_SECRET_KEY;
    const streamContractId = process.env.STREAM_CONTRACT_ID;

    if (!secretKey || !streamContractId) {
      console.error("FATAL: Missing SOROBAN_SECRET_KEY or STREAM_CONTRACT_ID in .env");
      process.exit(1);
    }

    try {
      const keypair = Keypair.fromSecret(secretKey);
      
      // SECURITY: The Soroban VM requires the receiver to authorize this call.
      // Prevent the user from wasting gas if they are using the wrong keystore.
      if (keypair.publicKey() !== options.receiver) {
        console.error("FATAL: Authorization mismatch.");
        console.error(`You are attempting to claim as: ${options.receiver}`);
        console.error(`But your .env identity is: ${keypair.publicKey()}`);
        console.error("Please update your .env with the receiver's secret key.");
        process.exit(1);
      }

      console.log(`Targeting Stream Contract: ${streamContractId}`);
      console.log(`Executing claim for receiver: ${keypair.publicKey()}...`);

      const client = new Client({
        networkPassphrase: 'Test SDF Network ; September 2015',
        contractId: streamContractId,
        rpcUrl: 'https://soroban-testnet.stellar.org:443',
        publicKey: keypair.publicKey(),
      });

      const txResponse = await client.claim({
        sender: options.sender,
        receiver: options.receiver,
      });

      console.log('SUCCESS: Tokens claimed and transferred on ledger!');
      console.log('Transaction Result:', txResponse);

    } catch (error: any) {
      console.error("FATAL: Claim transaction failed on-chain.");
      console.error(error?.response?.data || error.message || error);
      process.exit(1);
    }
  });

program
  .command('approve')
  .description('Grant the Stream Contract permission to spend your tokens')
  .requiredOption('-t, --token <address>', 'The token contract address (e.g., native XLM)')
  .requiredOption('-a, --amount <amount>', 'The maximum amount of tokens to approve')
  .action(async (options) => {
    const secretKey = process.env.SOROBAN_SECRET_KEY;
    const streamContractId = process.env.STREAM_CONTRACT_ID;

    if (!secretKey || !streamContractId) {
      console.error("FATAL: Missing SOROBAN_SECRET_KEY or STREAM_CONTRACT_ID in .env");
      process.exit(1);
    }

    try {
      const keypair = Keypair.fromSecret(secretKey);
      console.log(`Sender Identity: ${keypair.publicKey()}`);
      console.log(`Targeting Token Contract: ${options.token}`);
      
      const server = new rpc.Server('https://soroban-testnet.stellar.org:443');
      
      // 1. Fetch sequence number and latest ledger for the TTL calculation
      const account = await server.getAccount(keypair.publicKey());
      const latestLedger = await server.getLatestLedger();
      const expirationLedger = latestLedger.sequence + 500_000; // Valid for ~30 days

      console.log(`Setting allowance expiration to ledger: ${expirationLedger}`);

      // 2. Build the raw token approve operation (No bindings needed!)
      const tx = new TransactionBuilder(account, {
        fee: '10000',
        networkPassphrase: Networks.TESTNET,
      })
        .addOperation(Operation.invokeContractCall({
          contract: options.token,
          function: 'approve',
          args: [
            new Address(keypair.publicKey()).toScVal(),
            new Address(streamContractId).toScVal(),
            nativeToScVal(options.amount, { type: 'i128' }),
            nativeToScVal(expirationLedger, { type: 'u32' })
          ],
        }))
        .setTimeout(30)
        .build();

      console.log('Simulating transaction via RPC...');
      const preparedTx = await server.prepareTransaction(tx);
      
      preparedTx.sign(keypair);
      
      console.log('Submitting allowance to the ledger...');
      const txResponse = await server.sendTransaction(preparedTx);
      
      console.log(`SUCCESS: Tokens approved! Transaction Hash: ${txResponse.hash}`);
      
    } catch (error: any) {
      console.error("FATAL: Failed to approve tokens.");
      console.error(error?.response?.data || error.message || error);
      process.exit(1);
    }
  });

program.parse(process.argv);
