#!/usr/bin/env node
import { Command } from 'commander';
import * as dotenv from 'dotenv';
import { resolve } from 'path';
import { Keypair } from '@stellar/stellar-sdk';
import { Client } from './bindings/stream'; // Auto-generated by Sprint 2

// Securely load environment variables
dotenv.config({ path: resolve(__dirname, '../.env') });

const program = new Command();

program
  .name('orbitstream')
  .description('CLI to deploy and manage OrbitStream continuous funding contracts on Soroban')
  .version('0.1.0');

program
  .command('init')
  .description('Initialize a new funding stream configuration')
  .requiredOption('-r, --receiver <address>', 'The Stellar address of the open-source maintainer')
  .requiredOption('-t, --token <address>', 'The contract address of the token (e.g., USDC)')
  .requiredOption('-f, --flow-rate <amount>', 'The amount of tokens to stream per second')
  .action(async (options) => {
    const deployerSecret = process.env.SOROBAN_SECRET_KEY;
    const streamContractId = process.env.STREAM_CONTRACT_ID;

    if (!deployerSecret) {
      console.error("FATAL: SOROBAN_SECRET_KEY is missing from the .env file.");
      process.exit(1);
    }
    if (!streamContractId) {
      console.error("FATAL: STREAM_CONTRACT_ID is missing from the .env file. Run 'make deploy' first.");
      process.exit(1);
    }

    try {
      console.log(`Targeting Stream Contract: ${streamContractId}`);
      
      // Cryptographically derive the keypair in-memory
      const keypair = Keypair.fromSecret(deployerSecret);
      console.log(`Loaded deployer identity: ${keypair.publicKey()}`);

      // Initialize the generated Soroban Client
      const client = new Client({
        networkPassphrase: 'Test SDF Network ; September 2015',
        contractId: streamContractId,
        rpcUrl: 'https://soroban-testnet.stellar.org:443',
        publicKey: keypair.publicKey(),
      });

      console.log('Building and submitting transaction to Testnet...');
      
      // Execute the on-chain init method via the generated TS bindings
      // The bindings automatically map JS types to Rust types (flow_rate -> u64)
      const txResponse = await client.init({
        sender: keypair.publicKey(),
        receiver: options.receiver,
        token: options.token,
        flow_rate: BigInt(options.flowRate)
      });

      console.log('SUCCESS: Transaction confirmed on ledger!');
      console.log('Transaction Result:', txResponse);

    } catch (error: any) {
      console.error("FATAL: Transaction failed on-chain.");
      // Unpack VM panics or RPC errors for developer visibility
      console.error(error?.response?.data || error.message || error);
      process.exit(1);
    }
  });

program.parse(process.argv);
